DESCRIPTION: Remotes: Add missing comma
This fixes the following error:
```r
Error: Error: Missing commas separating Remotes: 'easystats/bayestestR
    easystats/see'
```